#################################################
# config.yaml
# 01 Aug 2013
# Said ÖZCAN									
# Twitter Printer
#################################################

consumerKey: 'NYAQD1pqIi7r5kjAezkdXw'

consumerSecret: 'K2lL3olWWhUm9AY6G0aeLeEo5xeMGaEsUq3ggeSDP4'

accessToken: '64197940-FaK7j72lvlXQqOSM53NjLKwMHczXuQuEgAtyDmzOI'

accessTokenSecret: '5ugAImEPoXZqSFKPKN09ecAWuOVCHRXi8fgsgfh4g'

delayTime: 30.0

pageTitle: 'TwitterPrinter'

searchHashtag: 'TwitterPrinter'

templateFileName: 'main.html'